# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Community Networks SIG
email: contact@cnsig.info
description: >- # this means to ignore newlines until "baseurl:"
  The Internet Society CNSIG serves as a vehicle through which Community Networks from around the world can develop, strengthen and promote the Community Network model, draft common strategies, share experiences and expertise, debate policy and regulatory issues and present their views.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cnsig.info" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  cnsig

# Build settings
markdown: kramdown
#theme: jekyll-theme-tactile
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

prose:
  rooturl: '_posts'
  siteurl: 'http://cnsig.github.io/'
  relativeLinks: 'http://cnsig.github.io/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
